services:
  client:
    build:
      context: ./lapse-delivery
      dockerfile: Dockerfile
    ports:
      - "19010:19000"
      - "19011:19001"
      - "19012:19002"
    volumes:
      - ./lapse-delivery:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/delivery:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=delivery.settings
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - rabbitmq

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3-management
    ports:
      - "5673:5672" # Standard AMQP port
      - "15673:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  rabbitmq_data:
