# Generated by Django 5.0.2 on 2025-06-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='road_worthiness_documents',
        ),
        migrations.AlterField(
            model_name='identityinformation',
            name='id_type',
            field=models.CharField(blank=True, choices=[('driver_license', 'Driver License'), ('passport', 'Passport'), ('government_id', 'Government ID')], default=None, max_length=20),
        ),
    ]
