# Generated by Django 5.0.2 on 2025-06-28 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_vehicle_road_worthiness_documents_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='road_worthiness',
            new_name='is_road_worthy',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='road_worthiness_expiry_date',
            new_name='last_inspection_date',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mot_documents',
            field=models.FileField(blank=True, null=True, upload_to='mot_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
